"""empty message

Revision ID: 3c28d85a10ed
Revises: 450b467b09bc
Create Date: 2025-12-08 15:40:17.735848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c28d85a10ed'
down_revision = '450b467b09bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        # add status with a server default so existing rows satisfy NOT NULL
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default=sa.text("'available'")))
        # create foreign keys with explicit names (required by Alembic batch operations)
        batch_op.create_foreign_key('fk_time_slots_student_id_user', 'user', ['student_id'], ['id'])
        batch_op.create_foreign_key('fk_time_slots_application_id_applications', 'applications', ['application_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_slots', schema=None) as batch_op:
        # drop the foreign key constraints by name
        batch_op.drop_constraint('fk_time_slots_application_id_applications', type_='foreignkey')
        batch_op.drop_constraint('fk_time_slots_student_id_user', type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('student_id')
        batch_op.drop_column('application_id')

    # ### end Alembic commands ###
